import turtle as tur
def screen_adjustment():
    scr = tur.Screen()
    scr.bgcolor('black')
    tur.title('Iron Maiden')
    tur.penup()
    tur.shape("turtle")
    tur.goto(-650, 100)
    #tur.pencolor((253,239,16,255))
    tur.pen(pencolor='Maroon' ,fillcolor="black", pensize=5)
    tur.pendown()  
    
def letter_i():
    tur.begin_fill()
    tur.fd(20)
    tur.rt(90)
    tur.fd(150)
    tur.lt(-90)
    tur.fd(20)
    tur.rt(90)
    tur.fd(150)
    tur.end_fill()
    
def letter_r():
    tur.penup()
    tur.goto(-610, 98)
    tur.pendown()
    tur.begin_fill()
    tur.rt(90)
    tur.fd(20)
    tur.rt(90)
    tur.fd(10)
    tur.rt(-130)
    tur.fd(30)
    tur.rt(90)
    tur.fd(75)
    tur.lt(-90)
    tur.fd(38)
    tur.lt(95)
    tur.fd(78)
    tur.lt(-90)
    tur.fd(20)
    tur.rt(90)
    tur.fd(120)
    tur.rt(225)
    tur.fd(90)
    tur.rt(90)
    tur.fd(20)
    tur.rt(90)
    tur.fd(145)
    tur.end_fill()
    
def letter_r_inside():
    tur.penup()
    tur.goto(-585, 60)
    tur.pendown()
    tur.begin_fill()
    tur.rt(50.2)
    tur.fd(22)
    tur.rt(75.2)
    tur.fd(26)
    tur.rt(144.5)
    tur.fd(36)
    
    tur.end_fill()
    
def letter_o():
    tur.penup()
    tur.goto(-450, 98)
    tur.pendown()
    tur.begin_fill()
    tur.rt(-45)
    tur.fd(105)
    tur.rt(-90.5)
    tur.fd(50)
    tur.rt(-45)
    tur.fd(70)
    tur.rt(-44.5)
    tur.fd(50)
    tur.rt(-86.5)
    tur.fd(98)
    tur.end_fill()
    
def letter_o_inside():
    tur.penup()
    tur.goto(-452, 78)
    tur.pendown()
    tur.begin_fill()
    tur.rt(-93.5)
    tur.fd(75)
    tur.rt(-90)
    tur.fd(30)
    tur.lt(45)
    tur.fd(60)
    tur.rt(-45)
    tur.fd(30)
    tur.rt(-88)
    tur.fd(73)
  
    tur.end_fill()
    
def letter_n():
    tur.penup()
    tur.goto(-372, 98)
    tur.pendown()
    tur.begin_fill()
    tur.rt(133.5)
    tur.fd(20)
    tur.rt(62.5)
    tur.fd(40)
    tur.rt(-152.5)
    tur.fd(35)
    tur.rt(90)
    tur.fd(20)
    tur.rt(89.7)
    tur.fd(170)
    tur.rt(145.5)
    tur.fd(35)
    tur.rt(34.5)
    tur.fd(35)
    tur.lt(35)
    tur.fd(35)
    tur.lt(144.5)
    tur.fd(50)
    tur.rt(90.5)
    tur.fd(20)
    tur.rt(88.8)
    tur.fd(109)
    tur.rt(-53.5)
    tur.fd(32)
    tur.rt(144.5)
    tur.fd(25)
    
    tur.end_fill()
    
     
def call_all_functions():
    screen_adjustment()
    letter_i()
    letter_r()
    letter_r_inside()
    letter_o()
    letter_o_inside()
    letter_n()
       
call_all_functions()
tur.hideturtle()
tur.exitonclick()
